services:
  redis:
    image: redis:7-alpine
    container_name: crypto_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crypto-net

  scraper:
    build: ./scraper
    container_name: crypto_scraper
    depends_on:
      - redis
    environment:
      - COINMARKETCAP_API_KEY=f6f6031f-2dd6-45c4-8b98-2df503c0efb2
    networks:
      - crypto-net

  consumer:
    build: ./consumer
    container_name: crypto_consumer
    depends_on:
      - redis
    volumes:
      - ./data:/data
    networks:
      - crypto-net

  dashboard:
    build: ./dashboard
    container_name: crypto_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - consumer
    volumes:
      - ./data:/data
    networks:
      - crypto-net

  streaming_server:
    build: ./streaming_server
    container_name: crypto_streaming
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - crypto-net
    restart: unless-stopped

volumes:
  redis_data:

networks:
  crypto-net:
    driver: bridge
    
